version: '3.8'
services:
  java-maven-app:
    image: kbarbary211/react-nodejs-example:latest
    ports:
      - "8080:8080"
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo-app
